### ISSUE TITLE
可以再详细点嘛，师傅

### ISSUE THREAD

**Issue by buji666** [veo/nginx_shell#2]
师傅，这个我按照步骤死活复现不出来 path也改了 权限也给了 也是1.18.0版本 就是死活复现不出来

**Comment by veo** [comment]
是Linux的吧？测试系统是Ubuntu

你可以试试docker的nginx 1.18.0，应该是没问题的

其实也有可能不是你的问题，是兼容性没到位。这个项目会以后也会继续发布研究兼容性的文章，优化对所有环境的支持

**Comment by buji666** [comment]
> 是Linux的吧？测试系统是Ubuntu
> 
> 你可以试试docker的nginx 1.18.0，应该是没问题的
> 
> 其实也有可能不是你的问题，是兼容性没到位。这个项目会以后也会继续发布研究兼容性的文章，优化对所有环境的支持

好的谢谢 我是用的docker起的 期待大佬后续的文章

**Comment by veo** [comment]
> 师傅，这个我按照步骤死活复现不出来 path也改了 权限也给了 也是1.18.0版本 就是死活复现不出来

可以尝试增加 `vtoken: whoami` header头的数量

**Comment by buji666** [comment]
> > 师傅，这个我按照步骤死活复现不出来 path也改了 权限也给了 也是1.18.0版本 就是死活复现不出来
> 
> 可以尝试增加 `vtoken: whoami` header头的数量

这个当时也是有尝试的，后续也找到了问题，使用一个完整的linux系统然后起nginx就成了，感谢大佬的指点！
