### ISSUE TITLE
nginx 1.24不支持了

### ISSUE THREAD

**Issue by sevck** [veo/nginx_shell#4]
首先感谢老哥提出的思路，根据代码二开了，更灵活的方式。
但是测试NGINX 1.24 应该这种方法不适用了，有其他的办法么？
还有就是默认www权限，想要持续维权root的话，老哥有什么办法么，除了修改配置user root

**Comment by veo** [comment]
不同版本可能是有点不同，得优化一下

默认www权限，想要持续维权root依赖nginx应该不行，因为nignx大概率是低权限用户起的。可以利用其它东西藏个后门就行，比如suid后门

**Comment by lmfcode** [comment]
> 不同版本可能是有点不同，得优化一下
> 
> 默认www权限，想要持续维权root依赖nginx应该不行，因为nignx大概率是低权限用户起的。可以利用其它东西藏个后门就行，比如suid后门

我在nginx version: nginx/1.24.0 (Ubuntu) 环境下做测试发现这个请求头的处理时候貌似有问题，不知道哪一步错了，除了Host头其他都乱了

![image](https://github.com/user-attachments/assets/075a8d41-ef38-46c5-9a0a-df7a44f9a37e)
